name: Deploy to Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: node --version
      - run: npm --version

      # install bun
      - name: Install bun
        run: npm install -g bun

      # install dependencies
      - name: Install dependencies
        run: bun install
      
      # build
      - name: Build
        run: bunx build

      # deploy
      - name: Deploy
        run: bunx start